---

- name: dnf update
  dnf:
    name: "*"
    state: latest

- name: install requirements packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ requirements_packages_dnf }}"

- name: install requirements pip packages
  pip:
    name: "{{ item }}"
  loop: "{{ requirements_packages_pip }}"

- name: install util packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ util_packages_dnf }}"

- name: install util pip packages
  pip:
    name: "{{ item }}"
  loop: "{{ util_packages_pip }}"

- name: git clone
  git:
    repo: https://github.com/ovn-org/ovn.git
    dest: "{{ ovn_dest_dir }}"
    version: v22.06.0

- name: boot.sh
  command: >-
    chdir={{ ovn_dest_dir }} ./boot.sh
  changed_when: true

- name: configure
  command: >-
    chdir={{ ovn_dest_dir }} ./configure
      --prefix=/usr
      --localstatedir=/var
      --sysconfdir=/etc
      --with-ovs-source={{ ovs_dest_dir}}
  changed_when: true

- name: make
  command: >-
    chdir={{ ovn_dest_dir }} make
  changed_when: true

- name: make install
  command: >-
    chdir={{ ovn_dest_dir }} make install
  changed_when: true
