---

- name: check openvswitch module
  command: >-
    lsmod
  register: lsmod
  changed_when: false

- name: enable openvswitch
  command: >-
    modprobe openvswitch
  changed_when: true
  when: not ("openvswitch" in lsmod.stdout)

- name: make directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ovs_etc_dir }}"
    - "{{ ovs_log_dir }}"
    - "{{ ovs_run_dir }}"
    - "{{ ovn_etc_dir }}"
    - "{{ ovn_log_dir }}"
    - "{{ ovn_run_dir }}"

- name: check vtep db
  stat:
    path: "{{ ovs_etc_dir }}/{{ ovs_vtep_db_name }}.db"
  register: vtep_db

- name: create vtep db schema
  command: >-
    ovsdb-tool create
      {{ ovs_etc_dir }}/{{ ovs_vtep_db_name }}.db
      {{ ovs_dest_dir }}/vtep/vtep.ovsschema
  changed_when: true
  when: not (vtep_db.stat.exists | bool)

- name: check conf db
  stat:
    path: "{{ ovs_etc_dir }}/{{ ovs_conf_db_name }}.db"
  register: conf_db

- name: create conf db schema
  command: >-
    ovsdb-tool create
      {{ ovs_etc_dir }}/{{ ovs_conf_db_name }}.db
      {{ ovs_dest_dir }}/vswitchd/vswitch.ovsschema
  changed_when: true
  when: not (conf_db.stat.exists | bool)

- name: check ovs_db pid
  stat:
    path: "{{ ovs_run_dir }}/{{ ovs_db_name }}.pid"
  register: ovs_db

- name: run ovs db
  command: >-
    ovsdb-server
      --remote=punix:{{ ovs_run_dir }}/{{ ovs_db_name }}.sock
      --detach
      --pidfile={{ ovs_run_dir }}/{{ ovs_db_name }}.pid
      --log-file={{ ovs_log_dir }}/{{ ovs_db_name }}.log
      {{ ovs_etc_dir }}/{{ ovs_vtep_db_name }}.db
      {{ ovs_etc_dir }}/{{ ovs_conf_db_name }}.db
  changed_when: true
  when: not (ovs_db.stat.exists | bool)

- name: init ovs db
  command: >-
    ovs-vsctl
      --db=unix:{{ ovs_run_dir }}/{{ ovs_db_name }}.sock
      --no-wait
      init
  changed_when: true
  when: not (ovs_db.stat.exists | bool)

- name: check vswitchd pid
  stat:
    path: "{{ ovs_run_dir }}/vswitchd.pid"
  register: vswitchd

- name: start vswitchd
  command: >-
    ovs-vswitchd
      --pidfile={{ ovs_run_dir }}/vswitchd.pid
      --detach
      --log-file={{ ovs_log_dir }}/vswitchd.log
      unix:{{ ovs_run_dir }}/{{ ovs_db_name }}.sock
  changed_when: true
  when: not (vswitchd.stat.exists | bool)

- name: setup system-id
  command: >-
    ovs-vsctl
      --db=unix:{{ ovs_run_dir }}/{{ ovs_db_name }}.sock
      set open .
      external-ids:system-id={{ ovn_system_ids[inventory_hostname] }}
  changed_when: true
  when: not (ovs_db.stat.exists | bool)

- name: setup ovn remote (sb)
  command: >-
    ovs-vsctl
      --db=unix:{{ ovs_run_dir }}/{{ ovs_db_name }}.sock
      set open .
      external-ids:ovn-remote=tcp:{{ ovn_remote_ip }}:{{ ovn_sb_port }}
  changed_when: true
  when: not (ovs_db.stat.exists | bool)

- name: setup encap-type
  command: >-
    ovs-vsctl
      --db=unix:{{ ovs_run_dir }}/{{ ovs_db_name }}.sock
      set open .
      external-ids:ovn-encap-type={{ ovn_encap_type }}
  changed_when: true
  when: not (ovs_db.stat.exists | bool)

- name: setup ovn encap-ip
  command: >-
    ovs-vsctl
      --db=unix:{{ ovs_run_dir }}/{{ ovs_db_name }}.sock
      set open .
      external-ids:ovn-encap-ip={{ ansible_host }}
  changed_when: true
  when: not (ovs_db.stat.exists | bool)

- name: check ovn-controller
  stat:
    path: "{{ ovn_run_dir }}/controller.pid"
  register: controller

- name: start ovn host
  command: >-
    ovn-controller
      --pidfile={{ ovn_run_dir }}/controller.pid
      --detach
      --log-file={{ ovn_log_dir }}/controller.log
      unix:{{ ovs_run_dir }}/{{ ovs_db_name }}.sock
  changed_when: true
  when: not (controller.stat.exists | bool)

- name: port open
  firewalld:
    zone: public
    port: "{{ ovn_encap_port }}/udp"
    permanent: yes
    immediate: yes
    state: enabled
