---

- name: dnf update
  dnf:
    name: "*"
    state: latest

- name: install requirements packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ requirements_packages_dnf }}"

- name: install requirements pip packages
  pip:
    name: "{{ item }}"
  loop: "{{ requirements_packages_pip }}"

- name: install util packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ util_packages_dnf }}"

- name: install util pip packages
  pip:
    name: "{{ item }}"
  loop: "{{ util_packages_pip }}"

- name: git clone
  git:
    repo: https://github.com/openvswitch/ovs.git
    dest: "{{ ovs_dest_dir }}"
    version: v3.0.0

- name: boot.sh
  command: >-
    chdir={{ ovs_dest_dir }} ./boot.sh
  changed_when: true

- name: configure
  command: >-
    chdir={{ ovs_dest_dir }} ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc
  changed_when: true

- name: make
  command: >-
    chdir={{ ovs_dest_dir }} make
  changed_when: true

- name: make install
  command: >-
    chdir={{ ovs_dest_dir }} make install
  changed_when: true
